version: 1
appRoot: nextjs
frontend:
  phases:
    build:
      commands:
        - npm ci --cache .npm --prefer-offline
        - npm run build
        - cd .next'
        - echo "DATABASE_URL=${DATABASE_URL}" > .env
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - .next/cache/**/*
      - .npm/**/*
      - node_modules/**/*
